services:
  s3:
    container_name: s3-container
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "airflow"
      MINIO_ROOT_PASSWORD: "airflow123"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure


  s3-service:
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-container:9000 airflow airflow123;
      /usr/bin/mc mb myminio/airflow;
      /usr/bin/mc mb myminio/mlflow;
      /usr/bin/mc mb myminio/lizvladi-mlops;
      /usr/bin/mc anonymous  set public myminio/airflow;
      /usr/bin/mc anonymous  set public myminio/mlflow;
      /usr/bin/mc anonymous  set public myminio/lizvladi-mlops;
      "

networks:
  default:
    external:
      name: airflow_network